#!/bin/python3
import os

path = os.path.abspath(os.curdir)

RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[0;32m'
YELLOW='\033[0;33m'

arr = [
    (r'<title>LCOV - file.info</title>', 
     r'<title>Анализ покрытия LCOV - file.info</title>'), 
    (r'<tr><td class="title">LCOV - code coverage report</td></tr>',
     r'<tr><td class="title">LCOV - отчет о покрытии кода</td></tr>'),

    (r'<td width="10%" class="headerItem">Current view:</td>',
     r'<td width="10%" class="headerItem">Текущий вид:</td>'),
    (r'<td width="35%" class="headerValue">top level</td>',
     r'<td width="35%" class="headerValue">общий отчет</td>'),
    (r'<td width="10%" class="headerCovTableHead">Hit</td>',
     r'<td width="10%" class="headerCovTableHead">Достигнуто</td>'),
    (r'<td width="10%" class="headerCovTableHead">Total</td>',
     r'<td width="10%" class="headerCovTableHead">Всего</td>'),
    (r'<td width="15%" class="headerCovTableHead">Coverage</td>',
     r'<td width="15%" class="headerCovTableHead">Покрытие</td>'),
    (r'<td class="headerItem">Test:</td>',
     r'<td class="headerItem">Тест:</td>'),
    (r'<td class="headerItem">Lines:</td>',
     r'<td class="headerItem">Строчки:</td>'),
    (r'<td class="headerItem">Date:</td>',
     r'<td class="headerItem">Дата:</td>'),
    (r'<td class="headerItem">Functions:</td>',
     r'<td class="headerItem">Функции:</td>'),
    (r'<td class="tableHead">Directory <span',
     r'<td class="tableHead">Папка <span'),
    (r'td class="tableHead" colspan=3>Line Coverage <span ',
     r'td class="tableHead" colspan=3>Покрытие Строчки<span '),
    (r'<td class="tableHead" colspan=2>Functions <',
     r'<td class="tableHead" colspan=2>Функции <'),
    (r'<tr><td class="versionInfo">Generated by:',
     r'<tr><td class="versionInfo"> Создан с использованием:'),
    (r'<td class="tableHead">Filename <span ',
     r'<td class="tableHead">Файл<span '),
    (r'>top level</a>',
     r'>Главная</a>'),
]

for i in arr:
    print(i[0])

def go(cur):
    for dr in os.listdir(cur):
        abs_path = os.path.join(cur, dr)
        if os.path.isdir(abs_path):
            go(abs_path)
        elif 'html' in dr:
            curFile = abs_path
            print('Find file {}['.format(YELLOW) +curFile+']{}'.format(NC))
            outStrs = ''
            with open(curFile, 'r') as f:            	
                for i in f:
                    for r in arr:
                        a = r[0]
                        b = r[1]
                        if a in i:
                            i = i.replace(a, b)
                            print('{}[old]{}{}'.format(YELLOW, NC, RED), a, end=NC)
                            print('{}[new]{}{}'.format(YELLOW, NC, GREEN), i, end=NC)                    
                    outStrs += i

            with open(curFile, 'w') as f:
            	f.write(outStrs)            	 

go(path)